### ISSUE TITLE
Injecting chai and mocha fails

### ISSUE THREAD

**Issue by maciejjankowski** [szagi3891/AMDLoader#3]
I am trying to run a test suite against a page by injecting chai, mocha and a test suite.
Unfortunately I get a weird error which I don't understand.
I believe this could be related to your library or maybe I am doing something wrong.

![image](https://cloud.githubusercontent.com/assets/2905995/14747296/bbcbeee0-08b3-11e6-98e9-9a7f21eb374a.png)

**Comment by szagi3891** [comment]
A jakie dostajesz błędy ? Na tym zrzucie ekranu widać tylko breakpointy ustawione.

**Comment by maciejjankowski** [comment]
Uncaught Error: amdLoader: errorNumber: 24.1->2

wywala się w linii 5, jak zmodyfikuję mochę, żeby uruchamiała tylko linię 17 to podpina się pod window i wtedy działa dobrze

**Comment by maciejjankowski** [comment]
tak to wpinam, ale to chyba bez znaczenia, bo wywala się na `define`

````
(function ( d, s, id ) {
  var js, fjs = d.getElementsByTagName( s )[0];
  if ( d.getElementById( id ) ) return;
  js = d.createElement( s );
  js.id = id;
  js.src = '//dl.dropboxusercontent.com/u/19020828/js/mocha/runTests.js';
  fjs.parentNode.insertBefore( js, fjs );
  console.log( 'in!' );
}( document, 'script', 'injx' ));
````

**Comment by szagi3891** [comment]
Czy mógłbyś zrobić prostą stronkę testową pokazującą ten problem ? Zdaje się że jest problem z ładowaniem modułów w formacie CommonJS. Można dorobić łatwo obsługę tego typu modułów.

**Comment by maciejjankowski** [comment]
http://eurosport.onet.pl/pilka-nozna/liga-europy

**Comment by szagi3891** [comment]
Jako że już wyjaśniliśmy przyczynę problemu poza tym zgłoszeniem to zamykam.
